name: Dependency review for pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-submission:
    runs-on: ubuntu-26.04-arm
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'
        env:
          ORG_GRADLE_PROJECT_KDGPUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_KDGPPassword: ${{ github.token }}

      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v4
        if: github.event_name == 'pull_request'
