name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  integrationTest:
    runs-on: ubuntu-26.04-arm
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Run integration tests
        run: ./gradlew :gradle-plugin:integrationTest --rerun
        env:
          ORG_GRADLE_PROJECT_KDGPUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_KDGPPassword: ${{ github.token }}
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: gradle-plugin/build/reports/tests/integrationTest
          name: 'gradle-integration-test-results'

  sandboxTest:
    runs-on: ubuntu-26.04-arm
    permissions:
      contents: read
      packages: read

    environment:
      name: SBX
      url: https://sbx/${{ github.ref }}

    env:
      ORG_GRADLE_PROJECT_SBX_API_CLIENT_SECRET: ${{ secrets.SBX_API_CLIENT_SECRET }}
      ORG_GRADLE_PROJECT_SBX_RT_CLIENT_SECRET: ${{ secrets.SBX_RT_CLIENT_SECRET }}
      ORG_GRADLE_PROJECT_KDGPUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_KDGPPassword: ${{ github.token }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Run sandbox tests
        run: ./gradlew :api:sandboxTest --rerun

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: api/build/reports/tests/sandboxTest
          name: 'sbx-test-results'

      - name: Run functional tests
        run: ./gradlew :gradle-plugin:functionalTest --rerun

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: gradle-plugin/build/reports/tests/functionalTest
          name: 'gradle-functional-test-results'
