name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-26.04-arm
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Build with Gradle
        run: ./gradlew build :generator:integrationTest

      - name: Detekt
        run: ./gradlew :mergeDetektSarif
        if: always()

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt

      - name: Create baseline to upload suppressed code-smells to GitHub
        run: ./gradlew deleteDetektBaseline :mergeDetektSarif -PignoreDetektFailures=true
      - name: Upload detekt baseline to Github
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detektBaseline
